version: '3.6'

services:
  efairy-backend:
    image: matsta25.tk:5000/efairy-backend:latest
    ports:
      - 8080:8080
    networks:
      - efairy-backend-horoscope-web-scraper
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  horoscope-web-scraper:
    image: matsta25.tk:5000/horoscope-web-scraper:latest
    depends_on:
      - efairy-backend
    networks:
      - efairy-backend-horoscope-web-scraper

  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8082:8082
    command: ["-Djboss.http.port=8082", "-Dkeycloak.profile.feature.upload_scripts=enabled"]
    networks:
      - efairy-backend-horoscope-web-scraper

  # frontend here

networks:
  efairy-backend-horoscope-web-scraper:
