# docker-compose -f docker-compose-keycloak-local.yml up

version: '3.6'

services:
  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
    - ./keycloak/efairytheme:/opt/jboss/keycloak/themes/efairytheme
    ports:
      - 8082:8082
    # TODO: "-Dkeycloak.frontendUrl=http://keyclock.efairy.matsta.tk/auth"
    command: ["-Djboss.http.port=8082", "-Dkeycloak.profile.feature.upload_scripts=enabled"]


