###
POST http://localhost:8082/auth/realms/efairy-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=efairy-backend&client_secret=22f1890d-7bee-432e-847a-0a3952d27be3&username=user&password=user

###
POST http://localhost:8082/auth/realms/efairy-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=efairy-backend&client_secret=22f1890d-7bee-432e-847a-0a3952d27be3&username=user2&password=user2

###
POST http://localhost:8082/auth/realms/efairy-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=efairy-backend&client_secret=22f1890d-7bee-432e-847a-0a3952d27be3&username=moderator&password=moderator
