###
POST http://localhost:8082/auth/realms/efairy-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=efairy-backend&client_secret=6d6ba3a2-aea2-49f3-901c-60c6e3e929e8&username=user&password=user

###
POST http://localhost:8082/auth/realms/efairy-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=efairy-backend&client_secret=6d6ba3a2-aea2-49f3-901c-60c6e3e929e8&username=user1&password=user1

###
POST http://localhost:8082/auth/realms/efairy-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=efairy-backend&client_secret=6d6ba3a2-aea2-49f3-901c-60c6e3e929e8&username=moderator&password=moderator

###
POST http://localhost:8082/auth/realms/efairy-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=efairy-backend&client_secret=6d6ba3a2-aea2-49f3-901c-60c6e3e929e8&username=admin&password=admin



