###
GET http://localhost:8080/api/v1/horoscope?zodiacSign=libra


###
POST http://localhost:8080/api/v1/batch/invoke-import-horoscope
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="horoscopeBatchInput.csv"

< ./horoscopeBatchInput.csv

###
GET http://localhost:8080/api/v1/question
Authorization: bearer {{access_token}}


###
POST http://localhost:8080/api/v1/question
Content-Type: text/plain
Authorization: bearer {{access_token}}


How are you?2


###
POST http://localhost:8080/api/v1/question/1/answer
Content-Type: text/plain

Im fine.

###
POST http://localhost:8082/auth/realms/efairy-realm/protocol/openid-connect/auth
Authorization: Bearer {{access_token}}

